# -*- coding: utf-8 -*-
"""PathDamage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUXfazjWu2hpYr9_epLuWw7oGVvM2FNq
"""

# ------------------------------
# STEP 0: Install YOLOv8
# ------------------------------
!pip install ultralytics --quiet

# ------------------------------
# STEP 1: Upload & Unzip Dataset
# ------------------------------
from google.colab import files
import zipfile, os, yaml
uploaded = files.upload()  # upload Blind_Path_Damage_v1i_yolov8.zip
zip_filename = list(uploaded.keys())[0]

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall("dataset")

print("✅ Extracted successfully")

for split in ["train", "valid", "test"]:
    img_path = f"dataset/{split}/images"
    if os.path.exists(img_path):
        print(f"{split}: {len(os.listdir(img_path))} images")
    else:
        print(f"⚠️ {split}/images not found!")

# ------------------------------
# STEP 2: Create data.yaml
# ------------------------------
yaml_path = "data.yaml"

data_yaml_content = {
    'train': 'dataset/train/images',
    'val':   'dataset/valid/images',
    'test':  'dataset/test/images',
    'nc':    3,
    'names': ['minor_damage', 'normal_path', 'severe_damage']
}
with open(yaml_path, 'w') as f:
    yaml.dump(data_yaml_content, f, default_flow_style=False)

print(f"✅ data.yaml created")
print(f"Classes ({data_yaml_content['nc']}):", data_yaml_content['names'])

# ------------------------------
# STEP 3: Train YOLOv8
# ------------------------------
!pip install ultralytics --quiet

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data=yaml_path,
    epochs=50,
    batch=16,
    imgsz=640,
    project="path_damage",
    name="yolov8_damage_detector",
    exist_ok=True
)

import os

# ------------------------------
# STEP 4: Load Best Weights
# ------------------------------
best_model  = YOLO(os.path.join("runs", "detect", "path_damage", "yolov8_damage_detector", "weights", "best.pt"))
class_names = data_yaml_content['names']
print("✅ Model loaded. Classes:", class_names)

# ------------------------------
# STEP 4.5: Loss Curves & Confusion Matrix
# ------------------------------
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from pathlib import Path

results_dir = Path("runs/detect/path_damage/yolov8_damage_detector")

# Loss Curves
csv_path = results_dir / "results.csv"
df = pd.read_csv(csv_path)
df.columns = df.columns.str.strip()

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle("Training Loss Curves", fontsize=16, fontweight='bold')

plots = [
    ("train/box_loss", "Train Box Loss",   axes[0][0]),
    ("train/cls_loss", "Train Class Loss", axes[0][1]),
    ("train/dfl_loss", "Train DFL Loss",   axes[0][2]),
    ("val/box_loss",   "Val Box Loss",     axes[1][0]),
    ("val/cls_loss",   "Val Class Loss",   axes[1][1]),
    ("val/dfl_loss",   "Val DFL Loss",     axes[1][2]),
]

for col, title, ax in plots:
    if col in df.columns:
        ax.plot(df["epoch"], df[col], linewidth=2, color="royalblue")
        ax.set_title(title, fontsize=12)
        ax.set_xlabel("Epoch")
        ax.grid(True, alpha=0.3)
    else:
        ax.set_title(f"{title} (not found)", fontsize=10)
        ax.axis("off")

plt.tight_layout()
plt.show()

# Confusion Matrix
conf_matrix_path = results_dir / "confusion_matrix_normalized.png"
if not conf_matrix_path.exists():
    conf_matrix_path = results_dir / "confusion_matrix.png"

if conf_matrix_path.exists():
    img = mpimg.imread(conf_matrix_path)
    plt.figure(figsize=(8, 6))
    plt.imshow(img)
    plt.title("Confusion Matrix", fontsize=14, fontweight='bold')
    plt.axis("off")
    plt.show()
else:
    print("⚠️ Confusion matrix not found.")

# ------------------------------
# STEP 5: Test on Top 4 Images
# ------------------------------
import matplotlib.patches as patches
from PIL import Image
import numpy as np

test_img_dir = "dataset/test/images"
all_images   = os.listdir(test_img_dir)

# Pick 4 images with highest confidence detections
scored = []
for img_name in all_images:
    test_img_path = os.path.join(test_img_dir, img_name)
    results = best_model.predict(test_img_path, conf=0.25, verbose=False)
    if len(results[0].boxes) > 0:
        top_conf = float(results[0].boxes.conf.max())
        scored.append((top_conf, img_name))

scored.sort(reverse=True)
test_images = [img_name for _, img_name in scored[:4]]

COLORS = {
    'minor_damage':  'orange',
    'normal_path':   'green',
    'severe_damage': 'red',
}

fig, axes = plt.subplots(1, 4, figsize=(20, 5))
fig.suptitle("Path Damage Detection — Top 4 Results", fontsize=14, fontweight='bold')

for ax, img_name in zip(axes, test_images):
    test_img_path = os.path.join(test_img_dir, img_name)
    results       = best_model.predict(test_img_path, conf=0.25, verbose=False)

    img = Image.open(test_img_path)
    ax.imshow(img)

    for box in results[0].boxes:
        x1, y1, x2, y2 = box.xyxy[0].tolist()
        cls   = int(box.cls[0])
        conf  = float(box.conf[0])
        label = f"{class_names[cls]}  {conf*100:.0f}%"
        color = COLORS.get(class_names[cls], 'red')

        rect = patches.Rectangle((x1, y1), x2-x1, y2-y1,
                                   linewidth=2, edgecolor=color, facecolor='none')
        ax.add_patch(rect)
        ax.text(x1, y1-5, label, color=color, fontsize=9, fontweight='bold')

    ax.axis("off")
    ax.set_title(img_name[:20], fontsize=8)

plt.tight_layout()
plt.show()

# ------------------------------
# STEP 6: Export Model
# ------------------------------
best_model.export(format="onnx")
best_model.export(format="torchscript")
print("✅ Models exported.")

# ------------------------------
# STEP 7: Download Model
# ------------------------------
import shutil
from google.colab import files # Ensure files is imported if not already

shutil.copy(
    "runs/detect/path_damage/yolov8_damage_detector/weights/best.pt",
    "blind_path_damage_best.pt"
)
files.download("blind_path_damage_best.pt")